### ISSUE TITLE
Add ability to read the TCL file from standard input instead of an actual file

### ISSUE THREAD

**Issue by SethGower** [nmoroze/tclint#26]
It would be useful to be able to read the file to be linted from standard input instead of a file in the Filesystem. This could help use this tool in more versatile ways (for example, as I mentioned in #25 right now I have it reading from a temporary file, which can be less performant).

**Comment by nmoroze** [comment]
Good suggestion. I've added support for the `-` idiom so the following no works: `echo puts "hello world" | tclint -`. Exploring this also realized there was a bug that caused `tclint` to crash when running something like `tclint /dev/stdin`. That's now fixed.

I've cut a release with these updates ([`v0.2.2`](https://github.com/nmoroze/tclint/releases/tag/v0.2.2)). I'm closing this issue, but I'm curious if this works for your use case (either way!), and definitely feel free to reopen if something doesn't seem quite right.

**Comment by SethGower** [comment]
Wow, thanks for the quick response! I wasn't expecting a response that quickly, much less the feature being implemented. It seems to be working, I can do it from the command line and can also do it from my editor using the `stdin` method. Thanks a lot!
