### ISSUE TITLE
glob support in exclude list

### ISSUE THREAD

**Issue by gadfort** [nmoroze/tclint#28]
It would be incredibly useful if there was some kind of glob support for exclude:
For example, `*/build/*` to exclude everything from directories in a `/build/`.

**Comment by nmoroze** [comment]
Good suggestion, will try to have something for this in the next release.

**Comment by nmoroze** [comment]
I ended up adding support for the [gitignore pattern format](https://git-scm.com/docs/gitignore#_pattern_format). I think this will be a nice improvement, given it's much more expressive than what I had before and is somewhat standardized.

Although this includes globs, now you should be able to just use an entry like `build/` for your example use case. The change is included in the latest release v0.2.3.
