### ISSUE TITLE
Support for UPF files

### ISSUE THREAD

**Issue by gadfort** [nmoroze/tclint#31]
UPF files also use tcl like sdc files.

**Comment by nmoroze** [comment]
Good suggestion, I'll add .upf (I'm guessing that's the extension?) to the default search list and also take the chance to make the extension list configurable.

**Comment by gadfort** [comment]
Yes, it's the extension, but configurable would be great as well.

**Comment by nmoroze** [comment]
Just pushed an update so upf files are now found by default when searching a directory. In addition, the set of extensions can be overridden with a new `extensions` configuration option.

These changes are released in v0.2.4.
